# Use an official Golang runtime as the base image
FROM golang:1.16

# Set the working directory in the container to /app
WORKDIR /app

# Copy the local package files to the container's workspace
ADD . /app

# Install any needed packages specified in go.mod
RUN go mod download

# Build the Go app
RUN go build -o main .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the app when the container launches
CMD ["./main"]